---
# tasks file for nginx
- name: Include OS-specific variables.
  include_vars: "{{ ansible_facts['distribution'] }}.yml"


- name: install nginx ubuntu
  include_tasks: ubuntu.yaml
  when: ansible_facts['distribution'] == "Ubuntu"

- name: copy nginx conf
  ansible.builtin.template:
    src:  templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  
- name: copy site conf  
  ansible.builtin.template:
    src: templates/nginx_site.conf.j2
    dest: /etc/nginx/sites-enabled/nginx_site.conf
  notify: start nginx

- name: open port
  community.general.ufw:
    name: Nginx HTTP
    rule: allow

- name: run servise
  ansible.builtin.service:
    name: "nginx"
    state: started   
    enabled: yes
  


