---
 - name: file copy modules
   hosts: all
   become: yes
   tasks:
      - name: copy file to 
        ansible.builtin.copy:
          src: /etc/hosts
          dest: /tmp/

      - name: add lines to file
        ansible.builtin.blockinfile:
          path: /etc/resolv.conf
          block: |
            nameserver 8.8.8.8
            nameserver 8.8.4.4
          state: present

      - name: verify checksum file
        ansible.builtin.stat:
          path: /tmp/hosts
          checksum_algorithm: md5
        register: result
        
      - ansible.builtin.debug:
          var: result.stat.checksum

      - name: fetch
        ansible.builtin.fetch:
          src: /etc/resolv.conf
          dest: /tmp/  