# - name: install apache
#   hosts: all
#   become: yes
#   tasks:
#     - block:
        - name: install on apache2 om Ubuntu
          ansible.builtin.apt:
            name: "{{ package }}"
            state: present
            
       
            
        # - name: run servise  apache2
        #   ansible.builtin.service:
        #     name: "{{ service }}"
        #     state: started   
        #     enabled: yes

        - name: open port 
          ansible.builtin.include_tasks:
            ufw.yaml
      # when: ansible_facts.distribution == "Ubuntu"      