- name: install apache
  hosts: all
  become: yes
  tasks:
    - block:
        - name: install nginx
          ansible.builtin.apt:
            name: nginx
            state: present
            

        - name: open port
          community.general.ufw:
            name: Nginx HTTP
            rule: allow
            
            
        - name: run servise
          ansible.builtin.service:
            name: "nginx"
            state: started   
            enabled: yes
      when: ansible_facts.distribution == "Ubuntu"      