- name: base provision
  hosts: all
  become: yes
  tasks:
  
  - name: Update repositories and upgrade
    apt:
      update_cache: yes
      upgrade: yes 
    when: ansible_facts.distribution == "Ubuntu"
    
  - name: add user ansible
    user:
      name: ansible
      groups: sudo
      shell: /bin/bash
     

  - name: add ssh key
    authorized_key:
      user: ansible
      state: present
      manage_dir: yes
      key: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"