- name: test registry
  hosts: srv
  become: true
  tasks:
    
    - ansible.builtin.shell: cat /etc/passwd
      register: passwd_cont
      when: ansible_facts.distribution == "Ubuntu"
    
    
    - ansible.builtin.debug:
        msg: "{{ passwd_cont.stdout_lines[5] }}"
      when: passwd_cont['rc'] == 0

      
    - ansible.builtin.debug:
        var: passwd_cont
      